# Generated by Django 5.0 on 2024-01-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.BigIntegerField(default=1),
        ),
    ]
